name: build rust

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

# Run workflow on tags starting with v (eg. v2, v1.2.0)
  push:
    branches: [ "master" ]
    paths:
      - ./games/rust/*
  pull_request:
    branches: [ "master" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: ./data_pipelines/dataeng_github_metrics/Dockerfile
          push: true # Will only build if this is not here
          tags: |
           ghcr.io/neilrush/rust:latest
